version: '2'
services:
  postgres:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=alto        
  alto:
    image: alto-boot:latest
    ports:
      - "8080:8080"        
    volumes:
        - ../data:/usr/local/alto-boot/data
        - ../text_data:/usr/local/alto-boot/text_data
